import { Guide } from './types';

export const GUIDES: Guide[] = [
  {
    id: '1',
    category: 'architecture',
    title: {
      he: 'עיצוב בתי עץ מודרניים',
      en: 'Modern Wood House Design',
      zh: '现代木屋设计',
      hi: 'आधुनिक लकड़ी के घर का डिज़ाइन',
      de: 'Modernes Holzhaus-Design',
      es: 'Diseño de casa de madera moderna',
      fr: 'Design de maison en bois moderne',
      ar: 'تصميم بيت خشبي حديث'
    },
    description: {
      he: 'איך לשלב עץ כהה עם חלונות זכוכית למראה יוקרתי ומזמין המשתלב בטבע.',
      en: 'How to combine dark wood with glass windows for a luxurious look that blends with nature.',
      zh: '如何将深色木材与玻璃窗结合，打造与自然融合的奢华外观。',
      hi: 'प्रकृति के साथ घुलने-मिलने वाले शानदार लुक के लिए गहरे रंग की लकड़ी को कांच की खिड़कियों के साथ कैसे मिलाएं।',
      de: 'Wie man dunkles Holz mit Glasfenstern kombiniert, um einen luxuriösen Look zu erzielen, der mit der Natur verschmilzt.',
      es: 'Cómo combinar madera oscura con ventanas de vidrio para un aspecto lujoso que se mezcla con la naturaleza.',
      fr: 'Comment combiner le bois sombre avec des fenêtres en verre pour un look luxueux qui se fond dans la nature.',
      ar: 'كيفية الجمع بين الخشب الداكن والنوافذ الزجاجية للحصول على مظهر فاخر يمتزج مع الطبيعة.'
    },
    steps: {
      he: ['הנחת יסודות מעץ אלון כהה.', 'שימוש בלוחות זכוכית למתן עומק.', 'הוספת טרסות רחבות.', 'תאורה נסתרת.', 'גג שטוח מאבן.', 'בריכת מים בכניסה.'],
      en: ['Lay dark oak foundations.', 'Use glass panes for depth.', 'Add wide terraces.', 'Hidden lighting.', 'Flat stone roof.', 'Water pool at entrance.'],
      zh: ['铺设深色橡木基础。', '使用玻璃窗增加深度。', '增加宽阔的露台。', '隐藏式照明。', '平石屋顶。', '入口处的水池。'],
      hi: ['डार्क ओक की नींव रखें।', 'गहराई के लिए कांच के पैन का उपयोग करें।', 'चौड़ी छतें जोड़ें।', 'छिपी हुई रोशनी।', 'फ्लैट पत्थर की छत।', 'प्रवेश द्वार पर पानी का पूल।'],
      de: ['Dunkle Eichenfundamente legen.', 'Glasscheiben für Tiefe verwenden.', 'Breite Terrassen hinzufügen.', 'Versteckte Beleuchtung.', 'Flaches Steindach.', 'Wasserbecken am Eingang.'],
      es: ['Colocar cimientos de roble oscuro.', 'Usar paneles de vidrio para dar profundidad.', 'Añadir terrazas amplias.', 'Iluminación oculta.', 'Techo de piedra plano.', 'Piscina de agua en la entrada.'],
      fr: ['Poser des fondations en chêne sombre.', 'Utiliser des vitres pour la profondeur.', 'Ajouter de larges terrasses.', 'Éclairage caché.', 'Toit en pierre plat.', 'Bassin d\'eau à l\'entrée.'],
      ar: ['وضع أساسات البلوط الداكن.', 'استخدم الألواح الزجاجية للعمق.', 'إضافة شرفات واسعة.', 'إضاءة مخفية.', 'سقف حجري مسطح.', 'بركة مياه عند المدخل.']
    },
    imageUrl: 'https://images.unsplash.com/photo-1615655406736-b37c4fabf923?auto=format&fit=crop&q=80&w=800',
    galleryImages: [
      'https://images.unsplash.com/photo-1607627000458-210e8d261178?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1595113316349-9fa4ee24f884?auto=format&fit=crop&q=80&w=800'
    ]
  },
  {
    id: '7',
    category: 'redstone',
    title: {
      he: 'דלת 2x2 אוטומטית',
      en: '2x2 Automatic Piston Door',
      zh: '2x2 自动活塞门',
      hi: '2x2 स्वचालित पिस्टन दरवाजा',
      de: '2x2 automatische Kolbentür',
      es: 'Puerta de pistón automática 2x2',
      fr: 'Porte à pistons automatique 2x2',
      ar: 'باب مكبس آلي 2x2'
    },
    description: {
      he: 'בניית דלת רדסטון חבויה שנפתחת בעזרת לוחות לחץ למראה סודי ומקצועי.',
      en: 'Building a hidden Redstone door that opens with pressure plates for a secret and professional look.',
      zh: '建造一个使用压力板开启的隐藏红石门，打造神秘且专业的外观。',
      hi: 'एक छिपा हुआ रेडस्टोन दरवाजा बनाना जो गुप्त और पेशेवर लुक के लिए प्रेशर प्लेट्स के साथ खुलता है।',
      de: 'Bau einer versteckten Redstone-Tür, die sich mit Druckplatten öffnet, für einen geheimen und professionellen Look.',
      es: 'Construcción de una puerta de Redstone oculta que se abre con placas de presión para un aspecto secreto y profesional.',
      fr: 'Construction d\'une porte Redstone cachée qui s\'ouvre avec des plaques de pression pour un look secret et professionnel.',
      ar: 'بناء باب ريدستون مخفي يفتح بصفائح الضغط للحصول على مظهر سري واحترافي.'
    },
    steps: {
      he: ['הצבת 4 בוכנות דביקות.', 'חיבור אבקת רדסטון ללוחות לחץ.', 'שימוש בלפיד רדסטון להיפוך סיגנל.', 'כיסוי המכניקה בבלוקים תואמים.', 'בדיקה משני הצדדים.'],
      en: ['Place 4 sticky pistons.', 'Connect redstone dust to pressure plates.', 'Use redstone torch to invert signal.', 'Cover mechanics with matching blocks.', 'Test from both sides.'],
      zh: ['放置4个粘性活塞。', '将红石粉连接到压力板。', '使用红石火把反转信号。', '用匹配的方块覆盖机械装置。', '从两侧测试。'],
      hi: ['4 स्टिकी पिस्टन लगाएं।', 'रेडस्टोन डस्ट को प्रेशर प्लेट्स से जोड़ें।', 'सिग्नल को उलटने के लिए रेडस्टोन टॉर्च का उपयोग करें।', 'मैकेनिक्स को मैचिंग ब्लॉक्स से कवर करें।', 'दोनों तरफ से परीक्षण करें।'],
      de: ['4 klebrige Kolben platzieren.', 'Redstone-Staub mit Druckplatten verbinden.', 'Redstone-Fackel zum Invertieren des Signals verwenden.', 'Mechanik mit passenden Blöcken abdecken.', 'Von beiden Seiten testen.'],
      es: ['Colocar 4 pistones pegajosos.', 'Conectar polvo de redstone a placas de presión.', 'Usar antorcha de redstone para invertir la señal.', 'Cubrir la mecánica con bloques a juego.', 'Probar desde ambos lados.'],
      fr: ['Placer 4 pistons collants.', 'Connecter la poudre de redstone aux plaques de pression.', 'Utiliser une torche redstone pour inverser le signal.', 'Couvrir la mécanique avec des blocs assortis.', 'Tester des deux côtés.'],
      ar: ['ضع 4 مكابس لزجة.', 'قم بتوصيل غبار الريدستون بصفائح الضغط.', 'استخدم شعلة الريدستون لعكس الإشارة.', 'تغطية الميكانيكا بكتل متطابقة.', 'اختبار من كلا الجانبين.']
    },
    imageUrl: 'https://images.unsplash.com/photo-1581291417067-285048fc850d?auto=format&fit=crop&q=80&w=800',
    galleryImages: ['https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&q=80&w=800']
  },
  {
    id: '8',
    category: 'survival',
    title: {
      he: 'בסיס הישרדות תת-קרקעי',
      en: 'Underground Survival Base',
      zh: '地下生存基地',
      hi: 'भूमिगत जीवन रक्षा आधार',
      de: 'Unterirdische Überlebensbasis',
      es: 'Base de supervivencia subterránea',
      fr: 'Base de survie souterraine',
      ar: 'قاعدة بقاء تحت الأرض'
    },
    description: {
      he: 'איך לתכנן בסיס מוגן ובטוח מתחת לאדמה עם כל המשאבים הדרושים.',
      en: 'How to plan a safe protected underground base with all necessary resources.',
      zh: '如何规划一个拥有所有必要资源的地下安全保护基地。',
      hi: 'सभी आवश्यक संसाधनों के साथ एक सुरक्षित संरक्षित भूमिगत आधार की योजना कैसे बनाएं।',
      de: 'Wie man eine sicher geschützte unterirdische Basis mit allen notwendigen Ressourcen plant.',
      es: 'Cómo planificar una base subterránea protegida y segura con todos los recursos necesarios.',
      fr: 'Comment planifier une base souterraine protégée et sûre avec toutes les ressources nécessaires.',
      ar: 'كيفية التخطيط لقاعدة محمية تحت الأرض مع جميع الموارد اللازمة.'
    },
    steps: {
      he: ['חפירת חלל מרכזי רחב.', 'חלוקה לחדרים (שינה, אחסון, חוה).', 'שימוש בזכוכית בתקרה לתאורה טבעית.', 'יצירת כניסה מוסתרת.', 'הוספת מערכת אוורור דקורטיבית.'],
      en: ['Dig a wide central space.', 'Divide into rooms (bed, storage, farm).', 'Use glass in ceiling for natural light.', 'Create a hidden entrance.', 'Add decorative ventilation system.'],
      zh: ['挖掘宽敞的中心空间。', '划分房间（卧室、仓库、农场）。', '天花板使用玻璃引入自然光。', '创建一个隐藏入口。', '增加装饰性通风系统。'],
      hi: ['एक चौड़ा केंद्रीय स्थान खोदें।', 'कमरों में विभाजित करें (बिस्तर, भंडारण, खेत)।', 'प्राकृतिक रोशनी के लिए छत में कांच का उपयोग करें।', 'एक छिपा हुआ प्रवेश द्वार बनाएं।', 'सजावटी वेंटिलेशन सिस्टम जोड़ें।'],
      de: ['Einen weiten zentralen Raum graben.', 'In Räume unterteilen (Schlafzimmer, Lager, Farm).', 'Glas in der Decke für natürliches Licht verwenden.', 'Einen versteckten Eingang erstellen.', 'Dekoratives Belüftungssystem hinzufügen.'],
      es: ['Cavar un espacio central amplio.', 'Dividir en habitaciones (dormitorio, almacén, granja).', 'Usar vidrio en el techo para luz natural.', 'Crear una entrada oculta.', 'Añadir sistema de ventilación decorativo.'],
      fr: ['Creuser un large espace central.', 'Diviser en pièces (lit, stockage, ferme).', 'Utiliser du verre au plafond pour la lumière naturelle.', 'Créer une entrée cachée.', 'Ajouter un système de ventilation décoratif.'],
      ar: ['حفر مساحة مركزية واسعة.', 'التقسيم إلى غرف (نوم، تخزين، مزرعة).', 'استخدم الزجاج في السقف للإضاءة الطبيعية.', 'إنشاء مدخل مخفي.', 'إضافة نظام تهوية ديكوري.']
    },
    imageUrl: 'https://images.unsplash.com/photo-1595113316349-9fa4ee24f884?auto=format&fit=crop&q=80&w=800'
  }
];

export const UI_STRINGS = {
  he: {
    heroTitle: 'GoldCraft',
    heroSub: 'הפוך את עולם הקוביות שלך ליצירת אדריכלות מופת.',
    learnBtn: 'התחל ללמוד',
    feedbackBtn: 'שלח משוב',
    featuresTitle1: 'טכניקות בנייה',
    featuresDesc1: 'למד להשתמש בבלוקים בצורה שלא חשבת עליה מעולם.',
    guidesTitle: 'מדריכי בנייה נבחרים',
    noGuides: 'לא נמצאו מדריכים בקטגוריה זו...',
    footerDesc: 'קהילת הבנייה המובילה בישראל למיינקראפט.',
    copyBtn: 'העתק מדריך',
    copied: 'הועתק!',
    fullGuide: 'למדריך המלא',
    categoryAll: 'הכל',
    categoryArch: 'עיצוב מבנים',
    categoryBridge: 'גשרים',
    categoryInterior: 'עיצוב פנים',
    categoryTnt: 'פיצוצים',
    categoryEnv: 'נוף וסביבה',
    categoryRedstone: 'רדסטון',
    categorySurvival: 'הישרדות',
    categoryPixel: 'פיקסל ארט'
  },
  en: {
    heroTitle: 'GoldCraft',
    heroSub: 'Turn your block world into an architectural masterpiece.',
    learnBtn: 'Start Learning',
    feedbackBtn: 'Send Feedback',
    featuresTitle1: 'Building Techniques',
    featuresDesc1: 'Learn to use blocks in ways you never thought of.',
    guidesTitle: 'Featured Guides',
    noGuides: 'No guides found in this category...',
    footerDesc: 'Leading building community for Minecraft.',
    copyBtn: 'Copy Guide',
    copied: 'Copied!',
    fullGuide: 'Full Guide',
    categoryAll: 'All',
    categoryArch: 'Architecture',
    categoryBridge: 'Bridges',
    categoryInterior: 'Interior',
    categoryTnt: 'Explosions',
    categoryEnv: 'Landscape',
    categoryRedstone: 'Redstone',
    categorySurvival: 'Survival',
    categoryPixel: 'Pixel Art'
  },
  zh: {
    heroTitle: 'GoldCraft',
    heroSub: '将您的方块世界变成建筑杰作。',
    learnBtn: '开始学习',
    feedbackBtn: '发送反馈',
    featuresTitle1: '建筑技巧',
    featuresDesc1: '学习以您从未想过的方式使用方块。',
    guidesTitle: '精选指南',
    noGuides: '该分类下未找到指南...',
    footerDesc: '领先的 Minecraft 建筑社区。',
    copyBtn: '复制指南',
    copied: '已复制！',
    fullGuide: '完整指南',
    categoryAll: '全部',
    categoryArch: '建筑',
    categoryBridge: '桥梁',
    categoryInterior: '室内',
    categoryTnt: '爆炸',
    categoryEnv: '景观',
    categoryRedstone: '红石',
    categorySurvival: '生存',
    categoryPixel: '像素画'
  },
  hi: {
    heroTitle: 'GoldCraft',
    heroSub: 'अपनी ब्लॉक दुनिया को एक वास्तुशिल्प उत्कृष्ट कृति में बदलें।',
    learnBtn: 'सीखना शुरू करें',
    feedbackBtn: 'प्रतिक्रिया भेजें',
    featuresTitle1: 'निर्माण तकनीक',
    featuresDesc1: 'ब्लॉक का ऐसे तरीकों से उपयोग करना सीखें जिनके बारे में आपने कभी सोचा नहीं था।',
    guidesTitle: 'चुनिंदा गाइड',
    noGuides: 'इस श्रेणी में कोई गाइड नहीं मिली...',
    footerDesc: 'Minecraft के लिए अग्रणी निर्माण समुदाय।',
    copyBtn: 'गाइड कॉपी करें',
    copied: 'कॉपी किया गया!',
    fullGuide: 'पूर्ण गाइड',
    categoryAll: 'सभी',
    categoryArch: 'वास्तुकला',
    categoryBridge: 'पुल',
    categoryInterior: 'आंतरिक',
    categoryTnt: 'विस्फोट',
    categoryEnv: 'लैंडस्केप',
    categoryRedstone: 'रेडस्टोन',
    categorySurvival: 'जीवन रक्षा',
    categoryPixel: 'पिक्सेल कला'
  },
  de: {
    heroTitle: 'GoldCraft',
    heroSub: 'Verwandeln Sie Ihre Blockwelt in ein architektonisches Meisterwerk.',
    learnBtn: 'Lernen beginnen',
    feedbackBtn: 'Feedback senden',
    featuresTitle1: 'Bautechniken',
    featuresDesc1: 'Lernen Sie, Blöcke auf eine Weise zu nutzen, an die Sie nie gedacht haben.',
    guidesTitle: 'Ausgewählte Guides',
    noGuides: 'Keine Guides in dieser Kategorie gefunden...',
    footerDesc: 'Führende Baugemeinschaft für Minecraft.',
    copyBtn: 'Guide kopieren',
    copied: 'Kopiert!',
    fullGuide: 'Vollständiger Guide',
    categoryAll: 'Alle',
    categoryArch: 'Architektur',
    categoryBridge: 'Brücken',
    categoryInterior: 'Innenraum',
    categoryTnt: 'Explosionen',
    categoryEnv: 'Landschaft',
    categoryRedstone: 'Redstone',
    categorySurvival: 'Überleben',
    categoryPixel: 'Pixelkunst'
  },
  es: {
    heroTitle: 'GoldCraft',
    heroSub: 'Convierte tu mundo de bloques en una obra maestra arquitectónica.',
    learnBtn: 'Empezar a aprender',
    feedbackBtn: 'Enviar comentarios',
    featuresTitle1: 'Técnicas de construcción',
    featuresDesc1: 'Aprende a usar bloques de formas que nunca imaginaste.',
    guidesTitle: 'Guías destacadas',
    noGuides: 'No se encontraron guías en esta categoría...',
    footerDesc: 'Comunidad de construcción líder para Minecraft.',
    copyBtn: 'Copiar guía',
    copied: '¡Copiado!',
    fullGuide: 'Guía completa',
    categoryAll: 'Todo',
    categoryArch: 'Arquitectura',
    categoryBridge: 'Puentes',
    categoryInterior: 'Interior',
    categoryTnt: 'Explosiones',
    categoryEnv: 'Paisaje',
    categoryRedstone: 'Redstone',
    categorySurvival: 'Supervivencia',
    categoryPixel: 'Arte de píxeles'
  },
  fr: {
    heroTitle: 'GoldCraft',
    heroSub: 'Transformez votre monde de blocs en un chef-d\'œuvre architectural.',
    learnBtn: 'Commencer à apprendre',
    feedbackBtn: 'Envoyer des commentaires',
    featuresTitle1: 'Techniques de construction',
    featuresDesc1: 'Apprenez à utiliser les blocs de manières inédites.',
    guidesTitle: 'Guides en vedette',
    noGuides: 'Aucun guide trouvé dans cette catégorie...',
    footerDesc: 'Première communauté de construction pour Minecraft.',
    copyBtn: 'Copier le guide',
    copied: 'Copié !',
    fullGuide: 'Guide complet',
    categoryAll: 'Tout',
    categoryArch: 'Architecture',
    categoryBridge: 'Ponts',
    categoryInterior: 'Intérieur',
    categoryTnt: 'Explosions',
    categoryEnv: 'Paysage',
    categoryRedstone: 'Redstone',
    categorySurvival: 'Survie',
    categoryPixel: 'Pixel Art'
  },
  ar: {
    heroTitle: 'GoldCraft',
    heroSub: 'حوّل عالم المكعبات الخاص بك إلى تحفة معمارية.',
    learnBtn: 'ابدأ التعلم',
    feedbackBtn: 'إرسال ملاحظات',
    featuresTitle1: 'تقنيات البناء',
    featuresDesc1: 'تعلم استخدام المكعبات بطرق لم تفكر فيها من قبل.',
    guidesTitle: 'الأدلة المختارة',
    noGuides: 'لم يتم العثור على أدلة في هذه الفئة...',
    footerDesc: 'مجتمع البناء الرائد في ماين كرافت.',
    copyBtn: 'نسخ الدليل',
    copied: 'تم النسخ!',
    fullGuide: 'الدليل الكامل',
    categoryAll: 'الكل',
    categoryArch: 'العمارة',
    categoryBridge: 'الجسور',
    categoryInterior: 'التصميم الداخلي',
    categoryTnt: 'الانفجارات',
    categoryEnv: 'المناظر الطبيعية',
    categoryRedstone: 'ريدستون',
    categorySurvival: 'البقاء',
    categoryPixel: 'فن البكسل'
  }
};
